language: generic
sudo: required
 
services:
    - docker

before_install:
    - docker build -t msekeran/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true msekeran/react-test npm test

after_success:
    - docker build -t msekeran/multi-client ./client
    - docker build -t msekeran/multi-nginx ./nginx
    - docker build -t msekeran/multi-server ./server
    - docker build -t msekeran/multi-worker ./worker

    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
    #take the images and push to docker hub
    - docker push msekeran/multi-client
    - docker push msekeran/multi-nginx
    - docker push msekeran/multi-server
    - docker push msekeran/multi-worker

#deploy:
   # edge: true
   # provider: elasticbeanstalk
   # region: us-east-2
   # app: multi-docker
    #env: MultiDocker-env
   # bucket_name:
    #bucket_path:
    #on:
   #     branch: master
   # access_key_id: $AWS_ACCESS_KEY
   # secret_access_key:
   #     secure: $AWS_SECRET_KEY

