FROM node:alpine
WORKDIR "/app"
COPY ./package.json ./


RUN npm config set proxy rgb-proxy.avl.com:8080
RUN npm config set https-proxy rgb-proxy.avl.com:8080
RUN npm install
RUN npm install --save-dev @testing-library/jest-dom


COPY . .
CMD ["npm","run","dev"]